package main

type Emoji struct {
	Name  string
	Group string
	Char  rune
}

var db = []Emoji{
	{"watch", "basic", '⌚'},
	{"hourglass done", "basic", '⌛'},
	{"fast", "basic", '⏩'},
	{"alarm clock", "basic", '⏰'},
	{"hourglass not done", "basic", '⏳'},
	{"white medium", "basic", '◽'},
	{"umbrella with rain drops", "basic", '☔'},
	{"hot beverage", "basic", '☕'},
	{"aries", "basic", '♈'},
	{"pisces", "basic", '♓'},
	{"wheelchair symbol", "basic", '♿'},
	{"anchor", "basic", '⚓'},
	{"high voltage", "basic", '⚡'},
	{"white circle", "basic", '⚪'},
	{"black circle", "basic", '⚫'},
	{"soccer ball", "basic", '⚽'},
	{"baseball", "basic", '⚾'},
	{"snowman without snow", "basic", '⛄'},
	{"sun behind cloud", "basic", '⛅'},
	{"ophiuchus", "basic", '⛎'},
	{"no entry", "basic", '⛔'},
	{"church", "basic", '⛪'},
	{"fountain", "basic", '⛲'},
	{"flag in hole", "basic", '⛳'},
	{"sailboat", "basic", '⛵'},
	{"tent", "basic", '⛺'},
	{"fuel pump", "basic", '⛽'},
	{"check mark button", "basic", '✅'},
	{"raised fist", "basic", '✊'},
	{"raised hand", "basic", '✋'},
	{"sparkles", "basic", '✨'},
	{"cross mark", "basic", '❌'},
	{"cross mark button", "basic", '❎'},
	{"red question mark", "basic", '❓'},
	{"white exclamation mark", "basic", '❕'},
	{"red exclamation mark", "basic", '❗'},
	{"plus", "basic", '➕'},
	{"divide", "basic", '➗'},
	{"curly loop", "basic", '➰'},
	{"double curly loop", "basic", '➿'},
	{"black large square", "basic", '⬛'},
	{"white large square", "basic", '⬜'},
	{"star", "basic", '⭐'},
	{"hollow red circle", "basic", '⭕'},
	{"mahjong red dragon", "basic", '🀄'},
	{"joker", "basic", '🃏'},
	{"ab button", "basic", '🆎'},
	{"cl button", "basic", '🆑'},
	{"vs button", "basic", '🆚'},
	{"japanese", "basic", '🈁'},
	{"japanese", "basic", '🈚'},
	{"japanese", "basic", '🈯'},
	{"japanese", "basic", '🈲'},
	{"japanese", "basic", '🈸'},
	{"japanese", "basic", '🉐'},
	{"cyclone", "basic", '🌀'},
	{"milky way", "basic", '🌌'},
	{"globe showing europe", "basic", '🌍'},
	{"globe showing asia", "basic", '🌏'},
	{"globe with meridians", "basic", '🌐'},
	{"new moon", "basic", '🌑'},
	{"waxing crescent moon", "basic", '🌒'},
	{"first quarter moon", "basic", '🌓'},
	{"full moon", "basic", '🌕'},
	{"waning gibbous moon", "basic", '🌖'},
	{"waning crescent moon", "basic", '🌘'},
	{"crescent moon", "basic", '🌙'},
	{"new moon face", "basic", '🌚'},
	{"first quarter moon face", "basic", '🌛'},
	{"last quarter moon face", "basic", '🌜'},
	{"full moon face", "basic", '🌝'},
	{"sun with face", "basic", '🌞'},
	{"glowing star", "basic", '🌟'},
	{"shooting star", "basic", '🌠'},
	{"hot dog", "basic", '🌭'},
	{"burrito", "basic", '🌯'},
	{"chestnut", "basic", '🌰'},
	{"seedling", "basic", '🌱'},
	{"evergreen tree", "basic", '🌲'},
	{"deciduous tree", "basic", '🌳'},
	{"palm tree", "basic", '🌴'},
	{"cactus", "basic", '🌵'},
	{"tulip", "basic", '🌷'},
	{"tangerine", "basic", '🍊'},
	{"lemon", "basic", '🍋'},
	{"banana", "basic", '🍌'},
	{"green apple", "basic", '🍏'},
	{"pear", "basic", '🍐'},
	{"peach", "basic", '🍑'},
	{"clinking beer mugs", "basic", '🍻'},
	{"baby bottle", "basic", '🍼'},
	{"bottle with popping cork", "basic", '🍾'},
	{"popcorn", "basic", '🍿'},
	{"ribbon", "basic", '🎀'},
	{"graduation cap", "basic", '🎓'},
	{"carousel horse", "basic", '🎠'},
	{"person surfing", "basic", '🏄'},
	{"sports medal", "basic", '🏅'},
	{"trophy", "basic", '🏆'},
	{"horse racing", "basic", '🏇'},
	{"american football", "basic", '🏈'},
	{"rugby football", "basic", '🏉'},
	{"person swimming", "basic", '🏊'},
	{"cricket game", "basic", '🏏'},
	{"ping pong", "basic", '🏓'},
	{"house", "basic", '🏠'},
	{"japanese post office", "basic", '🏣'},
	{"post office", "basic", '🏤'},
	{"hospital", "basic", '🏥'},
	{"castle", "basic", '🏰'},
	{"black flag", "basic", '🏴'},
	{"badminton", "basic", '🏸'},
	{"rabbit", "basic", '🐇'},
	{"cat", "basic", '🐈'},
	{"dragon", "basic", '🐉'},
	{"whale", "basic", '🐋'},
	{"snail", "basic", '🐌'},
	{"horse", "basic", '🐎'},
	{"ram", "basic", '🐏'},
	{"goat", "basic", '🐐'},
	{"ewe", "basic", '🐑'},
	{"monkey", "basic", '🐒'},
	{"rooster", "basic", '🐓'},
	{"chicken", "basic", '🐔'},
	{"dog", "basic", '🐕'},
	{"pig", "basic", '🐖'},
	{"boar", "basic", '🐗'},
	{"poodle", "basic", '🐩'},
	{"camel", "basic", '🐪'},
	{"two", "basic", '🐫'},
	{"eyes", "basic", '👀'},
	{"ear", "basic", '👂'},
	{"bust in silhouette", "basic", '👤'},
	{"busts in silhouette", "basic", '👥'},
	{"boy", "basic", '👦'},
	{"woman and man holding hands", "basic", '👫'},
	{"men holding hands", "basic", '👬'},
	{"women holding hands", "basic", '👭'},
	{"police officer", "basic", '👮'},
	{"speech balloon", "basic", '💬'},
	{"thought balloon", "basic", '💭'},
	{"white flower", "basic", '💮'},
	{"dollar banknote", "basic", '💵'},
	{"euro banknote", "basic", '💶'},
	{"pound banknote", "basic", '💷'},
	{"money with wings", "basic", '💸'},
	{"closed mailbox with raised flag", "basic", '📫'},
	{"open mailbox with raised flag", "basic", '📬'},
	{"open mailbox with lowered flag", "basic", '📭'},
	{"postbox", "basic", '📮'},
	{"postal horn", "basic", '📯'},
	{"newspaper", "basic", '📰'},
	{"mobile phone off", "basic", '📴'},
	{"no mobile phones", "basic", '📵'},
	{"antenna bars", "basic", '📶'},
	{"camera", "basic", '📷'},
	{"camera with flash", "basic", '📸'},
	{"video camera", "basic", '📹'},
	{"videocassette", "basic", '📼'},
	{"prayer beads", "basic", '📿'},
	{"repeat single button", "basic", '🔂'},
	{"clockwise vertical arrows", "basic", '🔃'},
	{"counterclockwise arrows button", "basic", '🔄'},
	{"muted speaker", "basic", '🔇'},
	{"speaker low volume", "basic", '🔈'},
	{"speaker medium volume", "basic", '🔉'},
	{"speaker high volume", "basic", '🔊'},
	{"bell", "basic", '🔔'},
	{"bell with slash", "basic", '🔕'},
	{"bookmark", "basic", '🔖'},
	{"water pistol", "basic", '🔫'},
	{"microscope", "basic", '🔬'},
	{"telescope", "basic", '🔭'},
	{"crystal ball", "basic", '🔮'},
	{"downwards button", "basic", '🔽'},
	{"kaaba", "basic", '🕋'},
	{"menorah", "basic", '🕎'},
	{"one o", "basic", '🕐'},
	{"one", "basic", '🕜'},
	{"man dancing", "basic", '🕺'},
	{"middle finger", "basic", '🖕'},
	{"vulcan salute", "basic", '🖖'},
	{"black heart", "basic", '🖤'},
	{"mount fuji", "basic", '🗻'},
	{"moai", "basic", '🗿'},
	{"grinning face", "basic", '😀'},
	{"beaming face with smiling eyes", "basic", '😁'},
	{"grinning squinting face", "basic", '😆'},
	{"smiling face with halo", "basic", '😇'},
	{"smiling face with horns", "basic", '😈'},
	{"winking face", "basic", '😉'},
	{"smiling face with heart", "basic", '😍'},
	{"smiling face with sunglasses", "basic", '😎'},
	{"smirking face", "basic", '😏'},
	{"neutral face", "basic", '😐'},
	{"expressionless face", "basic", '😑'},
	{"unamused face", "basic", '😒'},
	{"pensive face", "basic", '😔'},
	{"confused face", "basic", '😕'},
	{"confounded face", "basic", '😖'},
	{"kissing face", "basic", '😗'},
	{"face blowing a kiss", "basic", '😘'},
	{"kissing face with smiling eyes", "basic", '😙'},
	{"kissing face with closed eyes", "basic", '😚'},
	{"face with tongue", "basic", '😛'},
	{"winking face with tongue", "basic", '😜'},
	{"disappointed face", "basic", '😞'},
	{"worried face", "basic", '😟'},
	{"angry face", "basic", '😠'},
	{"sad but relieved face", "basic", '😥'},
	{"frowning face with open mouth", "basic", '😦'},
	{"anguished face", "basic", '😧'},
	{"fearful face", "basic", '😨'},
	{"tired face", "basic", '😫'},
	{"grimacing face", "basic", '😬'},
	{"loudly crying face", "basic", '😭'},
	{"face with open mouth", "basic", '😮'},
	{"hushed face", "basic", '😯'},
	{"anxious face with sweat", "basic", '😰'},
	{"flushed face", "basic", '😳'},
	{"sleeping face", "basic", '😴'},
	{"face with crossed", "basic", '😵'},
	{"face without mouth", "basic", '😶'},
	{"face with medical mask", "basic", '😷'},
	{"weary cat", "basic", '🙀'},
	{"slightly frowning face", "basic", '🙁'},
	{"face with rolling eyes", "basic", '🙄'},
	{"person gesturing no", "basic", '🙅'},
	{"folded hands", "basic", '🙏'},
	{"rocket", "basic", '🚀'},
	{"helicopter", "basic", '🚁'},
	{"locomotive", "basic", '🚂'},
	{"railway car", "basic", '🚃'},
	{"bullet train", "basic", '🚅'},
	{"train", "basic", '🚆'},
	{"metro", "basic", '🚇'},
	{"light rail", "basic", '🚈'},
	{"station", "basic", '🚉'},
	{"tram", "basic", '🚊'},
	{"tram car", "basic", '🚋'},
	{"bus", "basic", '🚌'},
	{"oncoming bus", "basic", '🚍'},
	{"trolleybus", "basic", '🚎'},
	{"bus stop", "basic", '🚏'},
	{"minibus", "basic", '🚐'},
	{"ambulance", "basic", '🚑'},
	{"police car", "basic", '🚓'},
	{"oncoming police car", "basic", '🚔'},
	{"taxi", "basic", '🚕'},
	{"oncoming taxi", "basic", '🚖'},
	{"automobile", "basic", '🚗'},
	{"oncoming automobile", "basic", '🚘'},
	{"sport utility vehicle", "basic", '🚙'},
	{"delivery truck", "basic", '🚚'},
	{"articulated lorry", "basic", '🚛'},
	{"aerial tramway", "basic", '🚡'},
	{"ship", "basic", '🚢'},
	{"person rowing boat", "basic", '🚣'},
	{"speedboat", "basic", '🚤'},
	{"horizontal traffic light", "basic", '🚥'},
	{"vertical traffic light", "basic", '🚦'},
	{"construction", "basic", '🚧'},
	{"no smoking", "basic", '🚭'},
	{"litter in bin sign", "basic", '🚮'},
	{"non", "basic", '🚱'},
	{"bicycle", "basic", '🚲'},
	{"no bicycles", "basic", '🚳'},
	{"person mountain biking", "basic", '🚵'},
	{"person walking", "basic", '🚶'},
	{"no pedestrians", "basic", '🚷'},
	{"children crossing", "basic", '🚸'},
	{"men", "basic", '🚹'},
	{"shower", "basic", '🚿'},
	{"person taking bath", "basic", '🛀'},
	{"bathtub", "basic", '🛁'},
	{"left luggage", "basic", '🛅'},
	{"person in bed", "basic", '🛌'},
	{"place of worship", "basic", '🛐'},
	{"stop sign", "basic", '🛑'},
	{"shopping cart", "basic", '🛒'},
	{"hindu temple", "basic", '🛕'},
	{"hut", "basic", '🛖'},
	{"elevator", "basic", '🛗'},
	{"wireless", "basic", '🛜'},
	{"playground slide", "basic", '🛝'},
	{"ring buoy", "basic", '🛟'},
	{"airplane departure", "basic", '🛫'},
	{"airplane arrival", "basic", '🛬'},
	{"kick scooter", "basic", '🛴'},
	{"canoe", "basic", '🛶'},
	{"sled", "basic", '🛷'},
	{"flying saucer", "basic", '🛸'},
	{"skateboard", "basic", '🛹'},
	{"auto rickshaw", "basic", '🛺'},
	{"pickup truck", "basic", '🛻'},
	{"roller skate", "basic", '🛼'},
	{"orange circle", "basic", '🟠'},
	{"brown square", "basic", '🟫'},
	{"heavy equals sign", "basic", '🟰'},
	{"pinched fingers", "basic", '🤌'},
	{"white heart", "basic", '🤍'},
	{"pinching hand", "basic", '🤏'},
	{"zipper", "basic", '🤐'},
	{"call me hand", "basic", '🤙'},
	{"crossed fingers", "basic", '🤞'},
	{"love", "basic", '🤟'},
	{"cowboy hat face", "basic", '🤠'},
	{"sneezing face", "basic", '🤧'},
	{"face with raised eyebrow", "basic", '🤨'},
	{"exploding head", "basic", '🤯'},
	{"pregnant woman", "basic", '🤰'},
	{"breast", "basic", '🤱'},
	{"selfie", "basic", '🤳'},
	{"person fencing", "basic", '🤺'},
	{"people wrestling", "basic", '🤼'},
	{"person playing handball", "basic", '🤾'},
	{"diving mask", "basic", '🤿'},
	{"wilted flower", "basic", '🥀'},
	{"goal net", "basic", '🥅'},
	{"", "basic", '🥇'},
	{"curling stone", "basic", '🥌'},
	{"lacrosse", "basic", '🥍'},
	{"flying disc", "basic", '🥏'},
	{"croissant", "basic", '🥐'},
	{"pancakes", "basic", '🥞'},
	{"dumpling", "basic", '🥟'},
	{"canned food", "basic", '🥫'},
	{"leafy green", "basic", '🥬'},
	{"smiling face with hearts", "basic", '🥰'},
	{"yawning face", "basic", '🥱'},
	{"smiling face with tear", "basic", '🥲'},
	{"partying face", "basic", '🥳'},
	{"cold face", "basic", '🥶'},
	{"ninja", "basic", '🥷'},
	{"disguised face", "basic", '🥸'},
	{"face holding back tears", "basic", '🥹'},
	{"pleading face", "basic", '🥺'},
	{"sari", "basic", '🥻'},
	{"lab coat", "basic", '🥼'},
	{"flat shoe", "basic", '🥿'},
	{"crab", "basic", '🦀'},
	{"unicorn", "basic", '🦄'},
	{"eagle", "basic", '🦅'},
	{"squid", "basic", '🦑'},
	{"giraffe", "basic", '🦒'},
	{"cricket", "basic", '🦗'},
	{"kangaroo", "basic", '🦘'},
	{"swan", "basic", '🦢'},
	{"mammoth", "basic", '🦣'},
	{"dodo", "basic", '🦤'},
	{"sloth", "basic", '🦥'},
	{"oyster", "basic", '🦪'},
	{"beaver", "basic", '🦫'},
	{"seal", "basic", '🦭'},
	{"guide dog", "basic", '🦮'},
	{"white cane", "basic", '🦯'},
	{"red hair", "basic", '🦰'},
	{"supervillain", "basic", '🦹'},
	{"safety vest", "basic", '🦺'},
	{"mechanical leg", "basic", '🦿'},
	{"cheese wedge", "basic", '🧀'},
	{"cupcake", "basic", '🧁'},
	{"salt", "basic", '🧂'},
	{"beverage box", "basic", '🧃'},
	{"ice", "basic", '🧊'},
	{"bubble tea", "basic", '🧋'},
	{"troll", "basic", '🧌'},
	{"person standing", "basic", '🧍'},
	{"deaf person", "basic", '🧏'},
	{"face with monocle", "basic", '🧐'},
	{"socks", "basic", '🧦'},
	{"red envelope", "basic", '🧧'},
	{"nazar amulet", "basic", '🧿'},
	{"ballet shoes", "basic", '🩰'},
	{"shorts", "basic", '🩳'},
	{"thong sandal", "basic", '🩴'},
	{"light blue heart", "basic", '🩵'},
	{"pink heart", "basic", '🩷'},
	{"drop of blood", "basic", '🩸'},
	{"stethoscope", "basic", '🩺'},
	{"x", "basic", '🩻'},
	{"yo", "basic", '🪀'},
	{"boomerang", "basic", '🪃'},
	{"nesting dolls", "basic", '🪆'},
	{"maracas", "basic", '🪇'},
	{"flute", "basic", '🪈'},
	{"ringed planet", "basic", '🪐'},
	{"banjo", "basic", '🪕'},
	{"military helmet", "basic", '🪖'},
	{"rock", "basic", '🪨'},
	{"mirror ball", "basic", '🪩'},
	{"hamsa", "basic", '🪬'},
	{"folding hand fan", "basic", '🪭'},
	{"khanda", "basic", '🪯'},
	{"fly", "basic", '🪰'},
	{"feather", "basic", '🪶'},
	{"lotus", "basic", '🪷'},
	{"nest with eggs", "basic", '🪺'},
	{"hyacinth", "basic", '🪻'},
	{"wing", "basic", '🪽'},
	{"goose", "basic", '🪿'},
	{"anatomical heart", "basic", '🫀'},
	{"people hugging", "basic", '🫂'},
	{"pregnant man", "basic", '🫃'},
	{"person with crown", "basic", '🫅'},
	{"moose", "basic", '🫎'},
	{"donkey", "basic", '🫏'},
	{"blueberries", "basic", '🫐'},
	{"teapot", "basic", '🫖'},
	{"pouring liquid", "basic", '🫗'},
	{"jar", "basic", '🫙'},
	{"ginger root", "basic", '🫚'},
	{"pea pod", "basic", '🫛'},
	{"melting face", "basic", '🫠'},
	{"bubbles", "basic", '🫧'},
	{"shaking face", "basic", '🫨'},
	{"hand with index finger and thumb crossed", "basic", '🫰'},
	{"heart hands", "basic", '🫶'},
	{"leftwards pushing hand", "basic", '🫷'},
	{"rightwards pushing hand", "basic", '🫸'},
	{"copyright", "basic", '©'},
	{"registered", "basic", '®'},
	{"double exclamation mark", "basic", '‼'},
	{"exclamation question mark", "basic", '⁉'},
	{"trade mark", "basic", '™'},
	{"information", "basic", 'ℹ'},
	{"left", "basic", '↔'},
	{"up", "basic", '↕'},
	{"up", "basic", '↖'},
	{"up", "basic", '↗'},
	{"down", "basic", '↘'},
	{"down", "basic", '↙'},
	{"right arrow curving left", "basic", '↩'},
	{"left arrow curving right", "basic", '↪'},
	{"keyboard", "basic", '⌨'},
	{"eject button", "basic", '⏏'},
	{"next track button", "basic", '⏭'},
	{"last track button", "basic", '⏮'},
	{"play or pause button", "basic", '⏯'},
	{"stopwatch", "basic", '⏱'},
	{"timer clock", "basic", '⏲'},
	{"pause button", "basic", '⏸'},
	{"stop button", "basic", '⏹'},
	{"record button", "basic", '⏺'},
	{"circled m", "basic", 'Ⓜ'},
	{"black small square", "basic", '▪'},
	{"white small square", "basic", '▫'},
	{"play button", "basic", '▶'},
	{"reverse button", "basic", '◀'},
	{"white medium square", "basic", '◻'},
	{"black medium square", "basic", '◼'},
	{"sun", "basic", '☀'},
	{"cloud", "basic", '☁'},
	{"umbrella", "basic", '☂'},
	{"snowman", "basic", '☃'},
	{"comet", "basic", '☄'},
	{"telephone", "basic", '☎'},
	{"check box with check", "basic", '☑'},
	{"shamrock", "basic", '☘'},
	{"index pointing up", "basic", '☝'},
	{"skull and crossbones", "basic", '☠'},
	{"radioactive", "basic", '☢'},
	{"biohazard", "basic", '☣'},
	{"orthodox cross", "basic", '☦'},
	{"star and crescent", "basic", '☪'},
	{"peace symbol", "basic", '☮'},
	{"yin yang", "basic", '☯'},
	{"wheel of dharma", "basic", '☸'},
	{"frowning face", "basic", '☹'},
	{"smiling face", "basic", '☺'},
	{"female sign", "basic", '♀'},
	{"male sign", "basic", '♂'},
	{"chess pawn", "basic", '♟'},
	{"spade suit", "basic", '♠'},
	{"club suit", "basic", '♣'},
	{"heart suit", "basic", '♥'},
	{"diamond suit", "basic", '♦'},
	{"hot springs", "basic", '♨'},
	{"recycling symbol", "basic", '♻'},
	{"infinity", "basic", '♾'},
	{"hammer and pick", "basic", '⚒'},
	{"crossed swords", "basic", '⚔'},
	{"medical symbol", "basic", '⚕'},
	{"balance scale", "basic", '⚖'},
	{"alembic", "basic", '⚗'},
	{"gear", "basic", '⚙'},
	{"atom symbol", "basic", '⚛'},
	{"fleur", "basic", '⚜'},
	{"warning", "basic", '⚠'},
	{"transgender symbol", "basic", '⚧'},
	{"coffin", "basic", '⚰'},
	{"funeral urn", "basic", '⚱'},
	{"cloud with lightning and rain", "basic", '⛈'},
	{"pick", "basic", '⛏'},
	{"rescue worker", "basic", '⛑'},
	{"chains", "basic", '⛓'},
	{"shinto shrine", "basic", '⛩'},
	{"mountain", "basic", '⛰'},
	{"umbrella on ground", "basic", '⛱'},
	{"ferry", "basic", '⛴'},
	{"skier", "basic", '⛷'},
	{"ice skate", "basic", '⛸'},
	{"person bouncing ball", "basic", '⛹'},
	{"scissors", "basic", '✂'},
	{"airplane", "basic", '✈'},
	{"envelope", "basic", '✉'},
	{"victory hand", "basic", '✌'},
	{"writing hand", "basic", '✍'},
	{"pencil", "basic", '✏'},
	{"black nib", "basic", '✒'},
	{"check mark", "basic", '✔'},
	{"multiply", "basic", '✖'},
	{"latin cross", "basic", '✝'},
	{"star of david", "basic", '✡'},
	{"eight", "basic", '✳'},
	{"eight", "basic", '✴'},
	{"snowflake", "basic", '❄'},
	{"sparkle", "basic", '❇'},
	{"heart exclamation", "basic", '❣'},
	{"red heart", "basic", '❤'},
	{"right arrow", "basic", '➡'},
	{"right arrow curving up", "basic", '⤴'},
	{"right arrow curving down", "basic", '⤵'},
	{"left arrow", "basic", '⬅'},
	{"up arrow", "basic", '⬆'},
	{"down arrow", "basic", '⬇'},
	{"wavy dash", "basic", '〰'},
	{"part alternation mark", "basic", '〽'},
	{"japanese", "basic", '㊗'},
	{"japanese", "basic", '㊙'},
	{"a button", "basic", '🅰'},
	{"b button", "basic", '🅱'},
	{"o button", "basic", '🅾'},
	{"p button", "basic", '🅿'},
	{"japanese", "basic", '🈂'},
	{"japanese", "basic", '🈷'},
	{"thermometer", "basic", '🌡'},
	{"sun behind small cloud", "basic", '🌤'},
	{"sun behind large cloud", "basic", '🌥'},
	{"sun behind rain cloud", "basic", '🌦'},
	{"cloud with rain", "basic", '🌧'},
	{"cloud with snow", "basic", '🌨'},
	{"cloud with lightning", "basic", '🌩'},
	{"tornado", "basic", '🌪'},
	{"fog", "basic", '🌫'},
	{"wind face", "basic", '🌬'},
	{"hot pepper", "basic", '🌶'},
	{"fork and knife with plate", "basic", '🍽'},
	{"military medal", "basic", '🎖'},
	{"reminder ribbon", "basic", '🎗'},
	{"studio microphone", "basic", '🎙'},
	{"level slider", "basic", '🎚'},
	{"control knobs", "basic", '🎛'},
	{"film frames", "basic", '🎞'},
	{"admission tickets", "basic", '🎟'},
	{"person lifting weights", "basic", '🏋'},
	{"person golfing", "basic", '🏌'},
	{"motorcycle", "basic", '🏍'},
	{"racing car", "basic", '🏎'},
	{"snow", "basic", '🏔'},
	{"camping", "basic", '🏕'},
	{"beach with umbrella", "basic", '🏖'},
	{"building construction", "basic", '🏗'},
	{"houses", "basic", '🏘'},
	{"cityscape", "basic", '🏙'},
	{"derelict house", "basic", '🏚'},
	{"classical building", "basic", '🏛'},
	{"desert", "basic", '🏜'},
	{"desert island", "basic", '🏝'},
	{"national park", "basic", '🏞'},
	{"stadium", "basic", '🏟'},
	{"white flag", "basic", '🏳'},
	{"rosette", "basic", '🏵'},
	{"label", "basic", '🏷'},
	{"chipmunk", "basic", '🐿'},
	{"eye", "basic", '👁'},
	{"film projector", "basic", '📽'},
	{"om", "basic", '🕉'},
	{"dove", "basic", '🕊'},
	{"candle", "basic", '🕯'},
	{"mantelpiece clock", "basic", '🕰'},
	{"hole", "basic", '🕳'},
	{"person in suit levitating", "basic", '🕴'},
	{"detective", "basic", '🕵'},
	{"sunglasses", "basic", '🕶'},
	{"spider", "basic", '🕷'},
	{"spider web", "basic", '🕸'},
	{"joystick", "basic", '🕹'},
	{"linked paperclips", "basic", '🖇'},
	{"pen", "basic", '🖊'},
	{"fountain pen", "basic", '🖋'},
	{"paintbrush", "basic", '🖌'},
	{"crayon", "basic", '🖍'},
	{"hand with fingers splayed", "basic", '🖐'},
	{"desktop computer", "basic", '🖥'},
	{"printer", "basic", '🖨'},
	{"computer mouse", "basic", '🖱'},
	{"trackball", "basic", '🖲'},
	{"framed picture", "basic", '🖼'},
	{"card index dividers", "basic", '🗂'},
	{"card file box", "basic", '🗃'},
	{"file cabinet", "basic", '🗄'},
	{"wastebasket", "basic", '🗑'},
	{"spiral notepad", "basic", '🗒'},
	{"spiral calendar", "basic", '🗓'},
	{"clamp", "basic", '🗜'},
	{"old key", "basic", '🗝'},
	{"rolled", "basic", '🗞'},
	{"dagger", "basic", '🗡'},
	{"speaking head", "basic", '🗣'},
	{"left speech bubble", "basic", '🗨'},
	{"right anger bubble", "basic", '🗯'},
	{"ballot box with ballot", "basic", '🗳'},
	{"world map", "basic", '🗺'},
	{"couch and lamp", "basic", '🛋'},
	{"shopping bags", "basic", '🛍'},
	{"bellhop bell", "basic", '🛎'},
	{"bed", "basic", '🛏'},
	{"hammer and wrench", "basic", '🛠'},
	{"shield", "basic", '🛡'},
	{"oil drum", "basic", '🛢'},
	{"motorway", "basic", '🛣'},
	{"railway track", "basic", '🛤'},
	{"motor boat", "basic", '🛥'},
	{"small airplane", "basic", '🛩'},
	{"satellite", "basic", '🛰'},
	{"passenger ship", "basic", '🛳'},
	{"keycap:", "keycap", '#'},
	{"keycap:", "keycap", '*'},
	{"keycap:", "keycap", '0'},
	{"keycap:", "keycap", '1'},
	{"keycap:", "keycap", '2'},
	{"keycap:", "keycap", '3'},
	{"keycap:", "keycap", '4'},
	{"keycap:", "keycap", '5'},
	{"keycap:", "keycap", '6'},
	{"keycap:", "keycap", '7'},
	{"keycap:", "keycap", '8'},
	{"keycap:", "keycap", '9'},
	{"flag: ascension island", "flag", '🇦'},
	{"flag: andorra", "flag", '🇦'},
	{"flag: united arab emirates", "flag", '🇦'},
	{"flag: afghanistan", "flag", '🇦'},
	{"flag: antigua", "flag", '🇦'},
	{"flag: anguilla", "flag", '🇦'},
	{"flag: albania", "flag", '🇦'},
	{"flag: armenia", "flag", '🇦'},
	{"flag: angola", "flag", '🇦'},
	{"flag: antarctica", "flag", '🇦'},
	{"flag: argentina", "flag", '🇦'},
	{"flag: american samoa", "flag", '🇦'},
	{"flag: austria", "flag", '🇦'},
	{"flag: australia", "flag", '🇦'},
	{"flag: aruba", "flag", '🇦'},
	{"flag:", "flag", '🇦'},
	{"flag: azerbaijan", "flag", '🇦'},
	{"flag: bosnia", "flag", '🇧'},
	{"flag: barbados", "flag", '🇧'},
	{"flag: bangladesh", "flag", '🇧'},
	{"flag: belgium", "flag", '🇧'},
	{"flag: burkina faso", "flag", '🇧'},
	{"flag: bulgaria", "flag", '🇧'},
	{"flag: bahrain", "flag", '🇧'},
	{"flag: burundi", "flag", '🇧'},
	{"flag: benin", "flag", '🇧'},
	{"flag: st", "flag", '🇧'},
	{"flag: bermuda", "flag", '🇧'},
	{"flag: brunei", "flag", '🇧'},
	{"flag: bolivia", "flag", '🇧'},
	{"flag: caribbean netherlands", "flag", '🇧'},
	{"flag: brazil", "flag", '🇧'},
	{"flag: bahamas", "flag", '🇧'},
	{"flag: bhutan", "flag", '🇧'},
	{"flag: bouvet island", "flag", '🇧'},
	{"flag: botswana", "flag", '🇧'},
	{"flag: belarus", "flag", '🇧'},
	{"flag: belize", "flag", '🇧'},
	{"flag: canada", "flag", '🇨'},
	{"flag: cocos", "flag", '🇨'},
	{"flag: congo", "flag", '🇨'},
	{"flag: central african republic", "flag", '🇨'},
	{"flag: congo", "flag", '🇨'},
	{"flag: switzerland", "flag", '🇨'},
	{"flag: c", "flag", '🇨'},
	{"flag: cook islands", "flag", '🇨'},
	{"flag: chile", "flag", '🇨'},
	{"flag: cameroon", "flag", '🇨'},
	{"flag: china", "flag", '🇨'},
	{"flag: colombia", "flag", '🇨'},
	{"flag: clipperton island", "flag", '🇨'},
	{"flag: costa rica", "flag", '🇨'},
	{"flag: cuba", "flag", '🇨'},
	{"flag: cape verde", "flag", '🇨'},
	{"flag: cura", "flag", '🇨'},
	{"flag: christmas island", "flag", '🇨'},
	{"flag: cyprus", "flag", '🇨'},
	{"flag: czechia", "flag", '🇨'},
	{"flag: germany", "flag", '🇩'},
	{"flag: diego garcia", "flag", '🇩'},
	{"flag: djibouti", "flag", '🇩'},
	{"flag: denmark", "flag", '🇩'},
	{"flag: dominica", "flag", '🇩'},
	{"flag: dominican republic", "flag", '🇩'},
	{"flag: algeria", "flag", '🇩'},
	{"flag: ceuta", "flag", '🇪'},
	{"flag: ecuador", "flag", '🇪'},
	{"flag: estonia", "flag", '🇪'},
	{"flag: egypt", "flag", '🇪'},
	{"flag: western sahara", "flag", '🇪'},
	{"flag: eritrea", "flag", '🇪'},
	{"flag: spain", "flag", '🇪'},
	{"flag: ethiopia", "flag", '🇪'},
	{"flag: european union", "flag", '🇪'},
	{"flag: finland", "flag", '🇫'},
	{"flag: fiji", "flag", '🇫'},
	{"flag: falkland islands", "flag", '🇫'},
	{"flag: micronesia", "flag", '🇫'},
	{"flag: faroe islands", "flag", '🇫'},
	{"flag: france", "flag", '🇫'},
	{"flag: gabon", "flag", '🇬'},
	{"flag: united kingdom", "flag", '🇬'},
	{"flag: grenada", "flag", '🇬'},
	{"flag: georgia", "flag", '🇬'},
	{"flag: french guiana", "flag", '🇬'},
	{"flag: guernsey", "flag", '🇬'},
	{"flag: ghana", "flag", '🇬'},
	{"flag: gibraltar", "flag", '🇬'},
	{"flag: greenland", "flag", '🇬'},
	{"flag: gambia", "flag", '🇬'},
	{"flag: guinea", "flag", '🇬'},
	{"flag: guadeloupe", "flag", '🇬'},
	{"flag: equatorial guinea", "flag", '🇬'},
	{"flag: greece", "flag", '🇬'},
	{"flag: south georgia", "flag", '🇬'},
	{"flag: guatemala", "flag", '🇬'},
	{"flag: guam", "flag", '🇬'},
	{"flag: guinea", "flag", '🇬'},
	{"flag: guyana", "flag", '🇬'},
	{"flag: hong kong sar china", "flag", '🇭'},
	{"flag: heard", "flag", '🇭'},
	{"flag: honduras", "flag", '🇭'},
	{"flag: croatia", "flag", '🇭'},
	{"flag: haiti", "flag", '🇭'},
	{"flag: hungary", "flag", '🇭'},
	{"flag: canary islands", "flag", '🇮'},
	{"flag: indonesia", "flag", '🇮'},
	{"flag: ireland", "flag", '🇮'},
	{"flag: israel", "flag", '🇮'},
	{"flag: isle of man", "flag", '🇮'},
	{"flag: india", "flag", '🇮'},
	{"flag: british indian ocean territory", "flag", '🇮'},
	{"flag: iraq", "flag", '🇮'},
	{"flag: iran", "flag", '🇮'},
	{"flag: iceland", "flag", '🇮'},
	{"flag: italy", "flag", '🇮'},
	{"flag: jersey", "flag", '🇯'},
	{"flag: jamaica", "flag", '🇯'},
	{"flag: jordan", "flag", '🇯'},
	{"flag: japan", "flag", '🇯'},
	{"flag: kenya", "flag", '🇰'},
	{"flag: kyrgyzstan", "flag", '🇰'},
	{"flag: cambodia", "flag", '🇰'},
	{"flag: kiribati", "flag", '🇰'},
	{"flag: comoros", "flag", '🇰'},
	{"flag: st", "flag", '🇰'},
	{"flag: north korea", "flag", '🇰'},
	{"flag: south korea", "flag", '🇰'},
	{"flag: kuwait", "flag", '🇰'},
	{"flag: cayman islands", "flag", '🇰'},
	{"flag: kazakhstan", "flag", '🇰'},
	{"flag: laos", "flag", '🇱'},
	{"flag: lebanon", "flag", '🇱'},
	{"flag: st", "flag", '🇱'},
	{"flag: liechtenstein", "flag", '🇱'},
	{"flag: sri lanka", "flag", '🇱'},
	{"flag: liberia", "flag", '🇱'},
	{"flag: lesotho", "flag", '🇱'},
	{"flag: lithuania", "flag", '🇱'},
	{"flag: luxembourg", "flag", '🇱'},
	{"flag: latvia", "flag", '🇱'},
	{"flag: libya", "flag", '🇱'},
	{"flag: morocco", "flag", '🇲'},
	{"flag: monaco", "flag", '🇲'},
	{"flag: moldova", "flag", '🇲'},
	{"flag: montenegro", "flag", '🇲'},
	{"flag: st", "flag", '🇲'},
	{"flag: madagascar", "flag", '🇲'},
	{"flag: marshall islands", "flag", '🇲'},
	{"flag: north macedonia", "flag", '🇲'},
	{"flag: mali", "flag", '🇲'},
	{"flag: myanmar", "flag", '🇲'},
	{"flag: mongolia", "flag", '🇲'},
	{"flag: macao sar china", "flag", '🇲'},
	{"flag: northern mariana islands", "flag", '🇲'},
	{"flag: martinique", "flag", '🇲'},
	{"flag: mauritania", "flag", '🇲'},
	{"flag: montserrat", "flag", '🇲'},
	{"flag: malta", "flag", '🇲'},
	{"flag: mauritius", "flag", '🇲'},
	{"flag: maldives", "flag", '🇲'},
	{"flag: malawi", "flag", '🇲'},
	{"flag: mexico", "flag", '🇲'},
	{"flag: malaysia", "flag", '🇲'},
	{"flag: mozambique", "flag", '🇲'},
	{"flag: namibia", "flag", '🇳'},
	{"flag: new caledonia", "flag", '🇳'},
	{"flag: niger", "flag", '🇳'},
	{"flag: norfolk island", "flag", '🇳'},
	{"flag: nigeria", "flag", '🇳'},
	{"flag: nicaragua", "flag", '🇳'},
	{"flag: netherlands", "flag", '🇳'},
	{"flag: norway", "flag", '🇳'},
	{"flag: nepal", "flag", '🇳'},
	{"flag: nauru", "flag", '🇳'},
	{"flag: niue", "flag", '🇳'},
	{"flag: new zealand", "flag", '🇳'},
	{"flag: oman", "flag", '🇴'},
	{"flag: panama", "flag", '🇵'},
	{"flag: peru", "flag", '🇵'},
	{"flag: french polynesia", "flag", '🇵'},
	{"flag: papua new guinea", "flag", '🇵'},
	{"flag: philippines", "flag", '🇵'},
	{"flag: pakistan", "flag", '🇵'},
	{"flag: poland", "flag", '🇵'},
	{"flag: st", "flag", '🇵'},
	{"flag: pitcairn islands", "flag", '🇵'},
	{"flag: puerto rico", "flag", '🇵'},
	{"flag: palestinian territories", "flag", '🇵'},
	{"flag: portugal", "flag", '🇵'},
	{"flag: palau", "flag", '🇵'},
	{"flag: paraguay", "flag", '🇵'},
	{"flag: qatar", "flag", '🇶'},
	{"flag: r", "flag", '🇷'},
	{"flag: romania", "flag", '🇷'},
	{"flag: serbia", "flag", '🇷'},
	{"flag: russia", "flag", '🇷'},
	{"flag: rwanda", "flag", '🇷'},
	{"flag: saudi arabia", "flag", '🇸'},
	{"flag: solomon islands", "flag", '🇸'},
	{"flag: seychelles", "flag", '🇸'},
	{"flag: sudan", "flag", '🇸'},
	{"flag: sweden", "flag", '🇸'},
	{"flag: singapore", "flag", '🇸'},
	{"flag: st", "flag", '🇸'},
	{"flag: slovenia", "flag", '🇸'},
	{"flag: svalbard", "flag", '🇸'},
	{"flag: slovakia", "flag", '🇸'},
	{"flag: sierra leone", "flag", '🇸'},
	{"flag: san marino", "flag", '🇸'},
	{"flag: senegal", "flag", '🇸'},
	{"flag: somalia", "flag", '🇸'},
	{"flag: suriname", "flag", '🇸'},
	{"flag: south sudan", "flag", '🇸'},
	{"flag: s", "flag", '🇸'},
	{"flag: el salvador", "flag", '🇸'},
	{"flag: sint maarten", "flag", '🇸'},
	{"flag: syria", "flag", '🇸'},
	{"flag: eswatini", "flag", '🇸'},
	{"flag: tristan da cunha", "flag", '🇹'},
	{"flag: turks", "flag", '🇹'},
	{"flag: chad", "flag", '🇹'},
	{"flag: french southern territories", "flag", '🇹'},
	{"flag: togo", "flag", '🇹'},
	{"flag: thailand", "flag", '🇹'},
	{"flag: tajikistan", "flag", '🇹'},
	{"flag: tokelau", "flag", '🇹'},
	{"flag: timor", "flag", '🇹'},
	{"flag: turkmenistan", "flag", '🇹'},
	{"flag: tunisia", "flag", '🇹'},
	{"flag: tonga", "flag", '🇹'},
	{"flag: t", "flag", '🇹'},
	{"flag: trinidad", "flag", '🇹'},
	{"flag: tuvalu", "flag", '🇹'},
	{"flag: taiwan", "flag", '🇹'},
	{"flag: tanzania", "flag", '🇹'},
	{"flag: ukraine", "flag", '🇺'},
	{"flag: uganda", "flag", '🇺'},
	{"flag: u", "flag", '🇺'},
	{"flag: united nations", "flag", '🇺'},
	{"flag: united states", "flag", '🇺'},
	{"flag: uruguay", "flag", '🇺'},
	{"flag: uzbekistan", "flag", '🇺'},
	{"flag: vatican city", "flag", '🇻'},
	{"flag: st", "flag", '🇻'},
	{"flag: venezuela", "flag", '🇻'},
	{"flag: british virgin islands", "flag", '🇻'},
	{"flag: u", "flag", '🇻'},
	{"flag: vietnam", "flag", '🇻'},
	{"flag: vanuatu", "flag", '🇻'},
	{"flag: wallis", "flag", '🇼'},
	{"flag: samoa", "flag", '🇼'},
	{"flag: kosovo", "flag", '🇽'},
	{"flag: yemen", "flag", '🇾'},
	{"flag: mayotte", "flag", '🇾'},
	{"flag: south africa", "flag", '🇿'},
	{"flag: zambia", "flag", '🇿'},
	{"flag: zimbabwe", "flag", '🇿'},
	{"flag: england", "tag", '🏴'},
	{"flag: scotland", "tag", '🏴'},
	{"flag: wales", "tag", '🏴'},
	{"index pointing up: light skin tone", "modifier", '☝'},
	{"index pointing up: medium", "modifier", '☝'},
	{"index pointing up: medium skin tone", "modifier", '☝'},
	{"index pointing up: medium", "modifier", '☝'},
	{"index pointing up: dark skin tone", "modifier", '☝'},
	{"person bouncing ball: light skin tone", "modifier", '⛹'},
	{"person bouncing ball: medium", "modifier", '⛹'},
	{"person bouncing ball: medium skin tone", "modifier", '⛹'},
	{"person bouncing ball: medium", "modifier", '⛹'},
	{"person bouncing ball: dark skin tone", "modifier", '⛹'},
	{"raised fist: light skin tone", "modifier", '✊'},
	{"raised fist: medium", "modifier", '✊'},
	{"raised fist: medium skin tone", "modifier", '✊'},
	{"raised fist: medium", "modifier", '✊'},
	{"raised fist: dark skin tone", "modifier", '✊'},
	{"raised hand: light skin tone", "modifier", '✋'},
	{"raised hand: medium", "modifier", '✋'},
	{"raised hand: medium skin tone", "modifier", '✋'},
	{"raised hand: medium", "modifier", '✋'},
	{"raised hand: dark skin tone", "modifier", '✋'},
	{"victory hand: light skin tone", "modifier", '✌'},
	{"victory hand: medium", "modifier", '✌'},
	{"victory hand: medium skin tone", "modifier", '✌'},
	{"victory hand: medium", "modifier", '✌'},
	{"victory hand: dark skin tone", "modifier", '✌'},
	{"writing hand: light skin tone", "modifier", '✍'},
	{"writing hand: medium", "modifier", '✍'},
	{"writing hand: medium skin tone", "modifier", '✍'},
	{"writing hand: medium", "modifier", '✍'},
	{"writing hand: dark skin tone", "modifier", '✍'},
	{"santa claus: light skin tone", "modifier", '🎅'},
	{"santa claus: medium", "modifier", '🎅'},
	{"santa claus: medium skin tone", "modifier", '🎅'},
	{"santa claus: medium", "modifier", '🎅'},
	{"santa claus: dark skin tone", "modifier", '🎅'},
	{"snowboarder: light skin tone", "modifier", '🏂'},
	{"snowboarder: medium", "modifier", '🏂'},
	{"snowboarder: medium skin tone", "modifier", '🏂'},
	{"snowboarder: medium", "modifier", '🏂'},
	{"snowboarder: dark skin tone", "modifier", '🏂'},
	{"person running: light skin tone", "modifier", '🏃'},
	{"person running: medium", "modifier", '🏃'},
	{"person running: medium skin tone", "modifier", '🏃'},
	{"person running: medium", "modifier", '🏃'},
	{"person running: dark skin tone", "modifier", '🏃'},
	{"person surfing: light skin tone", "modifier", '🏄'},
	{"person surfing: medium", "modifier", '🏄'},
	{"person surfing: medium skin tone", "modifier", '🏄'},
	{"person surfing: medium", "modifier", '🏄'},
	{"person surfing: dark skin tone", "modifier", '🏄'},
	{"horse racing: light skin tone", "modifier", '🏇'},
	{"horse racing: medium", "modifier", '🏇'},
	{"horse racing: medium skin tone", "modifier", '🏇'},
	{"horse racing: medium", "modifier", '🏇'},
	{"horse racing: dark skin tone", "modifier", '🏇'},
	{"person swimming: light skin tone", "modifier", '🏊'},
	{"person swimming: medium", "modifier", '🏊'},
	{"person swimming: medium skin tone", "modifier", '🏊'},
	{"person swimming: medium", "modifier", '🏊'},
	{"person swimming: dark skin tone", "modifier", '🏊'},
	{"person lifting weights: light skin tone", "modifier", '🏋'},
	{"person lifting weights: medium", "modifier", '🏋'},
	{"person lifting weights: medium skin tone", "modifier", '🏋'},
	{"person lifting weights: medium", "modifier", '🏋'},
	{"person lifting weights: dark skin tone", "modifier", '🏋'},
	{"person golfing: light skin tone", "modifier", '🏌'},
	{"person golfing: medium", "modifier", '🏌'},
	{"person golfing: medium skin tone", "modifier", '🏌'},
	{"person golfing: medium", "modifier", '🏌'},
	{"person golfing: dark skin tone", "modifier", '🏌'},
	{"ear: light skin tone", "modifier", '👂'},
	{"ear: medium", "modifier", '👂'},
	{"ear: medium skin tone", "modifier", '👂'},
	{"ear: medium", "modifier", '👂'},
	{"ear: dark skin tone", "modifier", '👂'},
	{"nose: light skin tone", "modifier", '👃'},
	{"nose: medium", "modifier", '👃'},
	{"nose: medium skin tone", "modifier", '👃'},
	{"nose: medium", "modifier", '👃'},
	{"nose: dark skin tone", "modifier", '👃'},
	{"backhand index pointing up: light skin tone", "modifier", '👆'},
	{"backhand index pointing up: medium", "modifier", '👆'},
	{"backhand index pointing up: medium skin tone", "modifier", '👆'},
	{"backhand index pointing up: medium", "modifier", '👆'},
	{"backhand index pointing up: dark skin tone", "modifier", '👆'},
	{"backhand index pointing down: light skin tone", "modifier", '👇'},
	{"backhand index pointing down: medium", "modifier", '👇'},
	{"backhand index pointing down: medium skin tone", "modifier", '👇'},
	{"backhand index pointing down: medium", "modifier", '👇'},
	{"backhand index pointing down: dark skin tone", "modifier", '👇'},
	{"backhand index pointing left: light skin tone", "modifier", '👈'},
	{"backhand index pointing left: medium", "modifier", '👈'},
	{"backhand index pointing left: medium skin tone", "modifier", '👈'},
	{"backhand index pointing left: medium", "modifier", '👈'},
	{"backhand index pointing left: dark skin tone", "modifier", '👈'},
	{"backhand index pointing right: light skin tone", "modifier", '👉'},
	{"backhand index pointing right: medium", "modifier", '👉'},
	{"backhand index pointing right: medium skin tone", "modifier", '👉'},
	{"backhand index pointing right: medium", "modifier", '👉'},
	{"backhand index pointing right: dark skin tone", "modifier", '👉'},
	{"oncoming fist: light skin tone", "modifier", '👊'},
	{"oncoming fist: medium", "modifier", '👊'},
	{"oncoming fist: medium skin tone", "modifier", '👊'},
	{"oncoming fist: medium", "modifier", '👊'},
	{"oncoming fist: dark skin tone", "modifier", '👊'},
	{"waving hand: light skin tone", "modifier", '👋'},
	{"waving hand: medium", "modifier", '👋'},
	{"waving hand: medium skin tone", "modifier", '👋'},
	{"waving hand: medium", "modifier", '👋'},
	{"waving hand: dark skin tone", "modifier", '👋'},
	{"ok hand: light skin tone", "modifier", '👌'},
	{"ok hand: medium", "modifier", '👌'},
	{"ok hand: medium skin tone", "modifier", '👌'},
	{"ok hand: medium", "modifier", '👌'},
	{"ok hand: dark skin tone", "modifier", '👌'},
	{"thumbs up: light skin tone", "modifier", '👍'},
	{"thumbs up: medium", "modifier", '👍'},
	{"thumbs up: medium skin tone", "modifier", '👍'},
	{"thumbs up: medium", "modifier", '👍'},
	{"thumbs up: dark skin tone", "modifier", '👍'},
	{"thumbs down: light skin tone", "modifier", '👎'},
	{"thumbs down: medium", "modifier", '👎'},
	{"thumbs down: medium skin tone", "modifier", '👎'},
	{"thumbs down: medium", "modifier", '👎'},
	{"thumbs down: dark skin tone", "modifier", '👎'},
	{"clapping hands: light skin tone", "modifier", '👏'},
	{"clapping hands: medium", "modifier", '👏'},
	{"clapping hands: medium skin tone", "modifier", '👏'},
	{"clapping hands: medium", "modifier", '👏'},
	{"clapping hands: dark skin tone", "modifier", '👏'},
	{"open hands: light skin tone", "modifier", '👐'},
	{"open hands: medium", "modifier", '👐'},
	{"open hands: medium skin tone", "modifier", '👐'},
	{"open hands: medium", "modifier", '👐'},
	{"open hands: dark skin tone", "modifier", '👐'},
	{"boy: light skin tone", "modifier", '👦'},
	{"boy: medium", "modifier", '👦'},
	{"boy: medium skin tone", "modifier", '👦'},
	{"boy: medium", "modifier", '👦'},
	{"boy: dark skin tone", "modifier", '👦'},
	{"girl: light skin tone", "modifier", '👧'},
	{"girl: medium", "modifier", '👧'},
	{"girl: medium skin tone", "modifier", '👧'},
	{"girl: medium", "modifier", '👧'},
	{"girl: dark skin tone", "modifier", '👧'},
	{"man: light skin tone", "modifier", '👨'},
	{"man: medium", "modifier", '👨'},
	{"man: medium skin tone", "modifier", '👨'},
	{"man: medium", "modifier", '👨'},
	{"man: dark skin tone", "modifier", '👨'},
	{"woman: light skin tone", "modifier", '👩'},
	{"woman: medium", "modifier", '👩'},
	{"woman: medium skin tone", "modifier", '👩'},
	{"woman: medium", "modifier", '👩'},
	{"woman: dark skin tone", "modifier", '👩'},
	{"woman and man holding hands: light skin tone", "modifier", '👫'},
	{"woman and man holding hands: medium", "modifier", '👫'},
	{"woman and man holding hands: medium skin tone", "modifier", '👫'},
	{"woman and man holding hands: medium", "modifier", '👫'},
	{"woman and man holding hands: dark skin tone", "modifier", '👫'},
	{"men holding hands: light skin tone", "modifier", '👬'},
	{"men holding hands: medium", "modifier", '👬'},
	{"men holding hands: medium skin tone", "modifier", '👬'},
	{"men holding hands: medium", "modifier", '👬'},
	{"men holding hands: dark skin tone", "modifier", '👬'},
	{"women holding hands: light skin tone", "modifier", '👭'},
	{"women holding hands: medium", "modifier", '👭'},
	{"women holding hands: medium skin tone", "modifier", '👭'},
	{"women holding hands: medium", "modifier", '👭'},
	{"women holding hands: dark skin tone", "modifier", '👭'},
	{"police officer: light skin tone", "modifier", '👮'},
	{"police officer: medium", "modifier", '👮'},
	{"police officer: medium skin tone", "modifier", '👮'},
	{"police officer: medium", "modifier", '👮'},
	{"police officer: dark skin tone", "modifier", '👮'},
	{"person with veil: light skin tone", "modifier", '👰'},
	{"person with veil: medium", "modifier", '👰'},
	{"person with veil: medium skin tone", "modifier", '👰'},
	{"person with veil: medium", "modifier", '👰'},
	{"person with veil: dark skin tone", "modifier", '👰'},
	{"person: light skin tone", "modifier", '👱'},
	{"person: medium", "modifier", '👱'},
	{"person: medium skin tone", "modifier", '👱'},
	{"person: medium", "modifier", '👱'},
	{"person: dark skin tone", "modifier", '👱'},
	{"person with skullcap: light skin tone", "modifier", '👲'},
	{"person with skullcap: medium", "modifier", '👲'},
	{"person with skullcap: medium skin tone", "modifier", '👲'},
	{"person with skullcap: medium", "modifier", '👲'},
	{"person with skullcap: dark skin tone", "modifier", '👲'},
	{"person wearing turban: light skin tone", "modifier", '👳'},
	{"person wearing turban: medium", "modifier", '👳'},
	{"person wearing turban: medium skin tone", "modifier", '👳'},
	{"person wearing turban: medium", "modifier", '👳'},
	{"person wearing turban: dark skin tone", "modifier", '👳'},
	{"old man: light skin tone", "modifier", '👴'},
	{"old man: medium", "modifier", '👴'},
	{"old man: medium skin tone", "modifier", '👴'},
	{"old man: medium", "modifier", '👴'},
	{"old man: dark skin tone", "modifier", '👴'},
	{"old woman: light skin tone", "modifier", '👵'},
	{"old woman: medium", "modifier", '👵'},
	{"old woman: medium skin tone", "modifier", '👵'},
	{"old woman: medium", "modifier", '👵'},
	{"old woman: dark skin tone", "modifier", '👵'},
	{"baby: light skin tone", "modifier", '👶'},
	{"baby: medium", "modifier", '👶'},
	{"baby: medium skin tone", "modifier", '👶'},
	{"baby: medium", "modifier", '👶'},
	{"baby: dark skin tone", "modifier", '👶'},
	{"construction worker: light skin tone", "modifier", '👷'},
	{"construction worker: medium", "modifier", '👷'},
	{"construction worker: medium skin tone", "modifier", '👷'},
	{"construction worker: medium", "modifier", '👷'},
	{"construction worker: dark skin tone", "modifier", '👷'},
	{"princess: light skin tone", "modifier", '👸'},
	{"princess: medium", "modifier", '👸'},
	{"princess: medium skin tone", "modifier", '👸'},
	{"princess: medium", "modifier", '👸'},
	{"princess: dark skin tone", "modifier", '👸'},
	{"baby angel: light skin tone", "modifier", '👼'},
	{"baby angel: medium", "modifier", '👼'},
	{"baby angel: medium skin tone", "modifier", '👼'},
	{"baby angel: medium", "modifier", '👼'},
	{"baby angel: dark skin tone", "modifier", '👼'},
	{"person tipping hand: light skin tone", "modifier", '💁'},
	{"person tipping hand: medium", "modifier", '💁'},
	{"person tipping hand: medium skin tone", "modifier", '💁'},
	{"person tipping hand: medium", "modifier", '💁'},
	{"person tipping hand: dark skin tone", "modifier", '💁'},
	{"guard: light skin tone", "modifier", '💂'},
	{"guard: medium", "modifier", '💂'},
	{"guard: medium skin tone", "modifier", '💂'},
	{"guard: medium", "modifier", '💂'},
	{"guard: dark skin tone", "modifier", '💂'},
	{"woman dancing: light skin tone", "modifier", '💃'},
	{"woman dancing: medium", "modifier", '💃'},
	{"woman dancing: medium skin tone", "modifier", '💃'},
	{"woman dancing: medium", "modifier", '💃'},
	{"woman dancing: dark skin tone", "modifier", '💃'},
	{"nail polish: light skin tone", "modifier", '💅'},
	{"nail polish: medium", "modifier", '💅'},
	{"nail polish: medium skin tone", "modifier", '💅'},
	{"nail polish: medium", "modifier", '💅'},
	{"nail polish: dark skin tone", "modifier", '💅'},
	{"person getting massage: light skin tone", "modifier", '💆'},
	{"person getting massage: medium", "modifier", '💆'},
	{"person getting massage: medium skin tone", "modifier", '💆'},
	{"person getting massage: medium", "modifier", '💆'},
	{"person getting massage: dark skin tone", "modifier", '💆'},
	{"person getting haircut: light skin tone", "modifier", '💇'},
	{"person getting haircut: medium", "modifier", '💇'},
	{"person getting haircut: medium skin tone", "modifier", '💇'},
	{"person getting haircut: medium", "modifier", '💇'},
	{"person getting haircut: dark skin tone", "modifier", '💇'},
	{"kiss: light skin tone", "modifier", '💏'},
	{"kiss: medium", "modifier", '💏'},
	{"kiss: medium skin tone", "modifier", '💏'},
	{"kiss: medium", "modifier", '💏'},
	{"kiss: dark skin tone", "modifier", '💏'},
	{"couple with heart: light skin tone", "modifier", '💑'},
	{"couple with heart: medium", "modifier", '💑'},
	{"couple with heart: medium skin tone", "modifier", '💑'},
	{"couple with heart: medium", "modifier", '💑'},
	{"couple with heart: dark skin tone", "modifier", '💑'},
	{"flexed biceps: light skin tone", "modifier", '💪'},
	{"flexed biceps: medium", "modifier", '💪'},
	{"flexed biceps: medium skin tone", "modifier", '💪'},
	{"flexed biceps: medium", "modifier", '💪'},
	{"flexed biceps: dark skin tone", "modifier", '💪'},
	{"person in suit levitating: light skin tone", "modifier", '🕴'},
	{"person in suit levitating: medium", "modifier", '🕴'},
	{"person in suit levitating: medium skin tone", "modifier", '🕴'},
	{"person in suit levitating: medium", "modifier", '🕴'},
	{"person in suit levitating: dark skin tone", "modifier", '🕴'},
	{"detective: light skin tone", "modifier", '🕵'},
	{"detective: medium", "modifier", '🕵'},
	{"detective: medium skin tone", "modifier", '🕵'},
	{"detective: medium", "modifier", '🕵'},
	{"detective: dark skin tone", "modifier", '🕵'},
	{"man dancing: light skin tone", "modifier", '🕺'},
	{"man dancing: medium", "modifier", '🕺'},
	{"man dancing: medium skin tone", "modifier", '🕺'},
	{"man dancing: medium", "modifier", '🕺'},
	{"man dancing: dark skin tone", "modifier", '🕺'},
	{"hand with fingers splayed: light skin tone", "modifier", '🖐'},
	{"hand with fingers splayed: medium", "modifier", '🖐'},
	{"hand with fingers splayed: medium skin tone", "modifier", '🖐'},
	{"hand with fingers splayed: medium", "modifier", '🖐'},
	{"hand with fingers splayed: dark skin tone", "modifier", '🖐'},
	{"middle finger: light skin tone", "modifier", '🖕'},
	{"middle finger: medium", "modifier", '🖕'},
	{"middle finger: medium skin tone", "modifier", '🖕'},
	{"middle finger: medium", "modifier", '🖕'},
	{"middle finger: dark skin tone", "modifier", '🖕'},
	{"vulcan salute: light skin tone", "modifier", '🖖'},
	{"vulcan salute: medium", "modifier", '🖖'},
	{"vulcan salute: medium skin tone", "modifier", '🖖'},
	{"vulcan salute: medium", "modifier", '🖖'},
	{"vulcan salute: dark skin tone", "modifier", '🖖'},
	{"person gesturing no: light skin tone", "modifier", '🙅'},
	{"person gesturing no: medium", "modifier", '🙅'},
	{"person gesturing no: medium skin tone", "modifier", '🙅'},
	{"person gesturing no: medium", "modifier", '🙅'},
	{"person gesturing no: dark skin tone", "modifier", '🙅'},
	{"person gesturing ok: light skin tone", "modifier", '🙆'},
	{"person gesturing ok: medium", "modifier", '🙆'},
	{"person gesturing ok: medium skin tone", "modifier", '🙆'},
	{"person gesturing ok: medium", "modifier", '🙆'},
	{"person gesturing ok: dark skin tone", "modifier", '🙆'},
	{"person bowing: light skin tone", "modifier", '🙇'},
	{"person bowing: medium", "modifier", '🙇'},
	{"person bowing: medium skin tone", "modifier", '🙇'},
	{"person bowing: medium", "modifier", '🙇'},
	{"person bowing: dark skin tone", "modifier", '🙇'},
	{"person raising hand: light skin tone", "modifier", '🙋'},
	{"person raising hand: medium", "modifier", '🙋'},
	{"person raising hand: medium skin tone", "modifier", '🙋'},
	{"person raising hand: medium", "modifier", '🙋'},
	{"person raising hand: dark skin tone", "modifier", '🙋'},
	{"raising hands: light skin tone", "modifier", '🙌'},
	{"raising hands: medium", "modifier", '🙌'},
	{"raising hands: medium skin tone", "modifier", '🙌'},
	{"raising hands: medium", "modifier", '🙌'},
	{"raising hands: dark skin tone", "modifier", '🙌'},
	{"person frowning: light skin tone", "modifier", '🙍'},
	{"person frowning: medium", "modifier", '🙍'},
	{"person frowning: medium skin tone", "modifier", '🙍'},
	{"person frowning: medium", "modifier", '🙍'},
	{"person frowning: dark skin tone", "modifier", '🙍'},
	{"person pouting: light skin tone", "modifier", '🙎'},
	{"person pouting: medium", "modifier", '🙎'},
	{"person pouting: medium skin tone", "modifier", '🙎'},
	{"person pouting: medium", "modifier", '🙎'},
	{"person pouting: dark skin tone", "modifier", '🙎'},
	{"folded hands: light skin tone", "modifier", '🙏'},
	{"folded hands: medium", "modifier", '🙏'},
	{"folded hands: medium skin tone", "modifier", '🙏'},
	{"folded hands: medium", "modifier", '🙏'},
	{"folded hands: dark skin tone", "modifier", '🙏'},
	{"person rowing boat: light skin tone", "modifier", '🚣'},
	{"person rowing boat: medium", "modifier", '🚣'},
	{"person rowing boat: medium skin tone", "modifier", '🚣'},
	{"person rowing boat: medium", "modifier", '🚣'},
	{"person rowing boat: dark skin tone", "modifier", '🚣'},
	{"person biking: light skin tone", "modifier", '🚴'},
	{"person biking: medium", "modifier", '🚴'},
	{"person biking: medium skin tone", "modifier", '🚴'},
	{"person biking: medium", "modifier", '🚴'},
	{"person biking: dark skin tone", "modifier", '🚴'},
	{"person mountain biking: light skin tone", "modifier", '🚵'},
	{"person mountain biking: medium", "modifier", '🚵'},
	{"person mountain biking: medium skin tone", "modifier", '🚵'},
	{"person mountain biking: medium", "modifier", '🚵'},
	{"person mountain biking: dark skin tone", "modifier", '🚵'},
	{"person walking: light skin tone", "modifier", '🚶'},
	{"person walking: medium", "modifier", '🚶'},
	{"person walking: medium skin tone", "modifier", '🚶'},
	{"person walking: medium", "modifier", '🚶'},
	{"person walking: dark skin tone", "modifier", '🚶'},
	{"person taking bath: light skin tone", "modifier", '🛀'},
	{"person taking bath: medium", "modifier", '🛀'},
	{"person taking bath: medium skin tone", "modifier", '🛀'},
	{"person taking bath: medium", "modifier", '🛀'},
	{"person taking bath: dark skin tone", "modifier", '🛀'},
	{"person in bed: light skin tone", "modifier", '🛌'},
	{"person in bed: medium", "modifier", '🛌'},
	{"person in bed: medium skin tone", "modifier", '🛌'},
	{"person in bed: medium", "modifier", '🛌'},
	{"person in bed: dark skin tone", "modifier", '🛌'},
	{"pinched fingers: light skin tone", "modifier", '🤌'},
	{"pinched fingers: medium", "modifier", '🤌'},
	{"pinched fingers: medium skin tone", "modifier", '🤌'},
	{"pinched fingers: medium", "modifier", '🤌'},
	{"pinched fingers: dark skin tone", "modifier", '🤌'},
	{"pinching hand: light skin tone", "modifier", '🤏'},
	{"pinching hand: medium", "modifier", '🤏'},
	{"pinching hand: medium skin tone", "modifier", '🤏'},
	{"pinching hand: medium", "modifier", '🤏'},
	{"pinching hand: dark skin tone", "modifier", '🤏'},
	{"sign of the horns: light skin tone", "modifier", '🤘'},
	{"sign of the horns: medium", "modifier", '🤘'},
	{"sign of the horns: medium skin tone", "modifier", '🤘'},
	{"sign of the horns: medium", "modifier", '🤘'},
	{"sign of the horns: dark skin tone", "modifier", '🤘'},
	{"call me hand: light skin tone", "modifier", '🤙'},
	{"call me hand: medium", "modifier", '🤙'},
	{"call me hand: medium skin tone", "modifier", '🤙'},
	{"call me hand: medium", "modifier", '🤙'},
	{"call me hand: dark skin tone", "modifier", '🤙'},
	{"raised back of hand: light skin tone", "modifier", '🤚'},
	{"raised back of hand: medium", "modifier", '🤚'},
	{"raised back of hand: medium skin tone", "modifier", '🤚'},
	{"raised back of hand: medium", "modifier", '🤚'},
	{"raised back of hand: dark skin tone", "modifier", '🤚'},
	{"left", "modifier", '🤛'},
	{"left", "modifier", '🤛'},
	{"left", "modifier", '🤛'},
	{"left", "modifier", '🤛'},
	{"left", "modifier", '🤛'},
	{"right", "modifier", '🤜'},
	{"right", "modifier", '🤜'},
	{"right", "modifier", '🤜'},
	{"right", "modifier", '🤜'},
	{"right", "modifier", '🤜'},
	{"handshake: light skin tone", "modifier", '🤝'},
	{"handshake: medium", "modifier", '🤝'},
	{"handshake: medium skin tone", "modifier", '🤝'},
	{"handshake: medium", "modifier", '🤝'},
	{"handshake: dark skin tone", "modifier", '🤝'},
	{"crossed fingers: light skin tone", "modifier", '🤞'},
	{"crossed fingers: medium", "modifier", '🤞'},
	{"crossed fingers: medium skin tone", "modifier", '🤞'},
	{"crossed fingers: medium", "modifier", '🤞'},
	{"crossed fingers: dark skin tone", "modifier", '🤞'},
	{"love", "modifier", '🤟'},
	{"love", "modifier", '🤟'},
	{"love", "modifier", '🤟'},
	{"love", "modifier", '🤟'},
	{"love", "modifier", '🤟'},
	{"person facepalming: light skin tone", "modifier", '🤦'},
	{"person facepalming: medium", "modifier", '🤦'},
	{"person facepalming: medium skin tone", "modifier", '🤦'},
	{"person facepalming: medium", "modifier", '🤦'},
	{"person facepalming: dark skin tone", "modifier", '🤦'},
	{"pregnant woman: light skin tone", "modifier", '🤰'},
	{"pregnant woman: medium", "modifier", '🤰'},
	{"pregnant woman: medium skin tone", "modifier", '🤰'},
	{"pregnant woman: medium", "modifier", '🤰'},
	{"pregnant woman: dark skin tone", "modifier", '🤰'},
	{"breast", "modifier", '🤱'},
	{"breast", "modifier", '🤱'},
	{"breast", "modifier", '🤱'},
	{"breast", "modifier", '🤱'},
	{"breast", "modifier", '🤱'},
	{"palms up together: light skin tone", "modifier", '🤲'},
	{"palms up together: medium", "modifier", '🤲'},
	{"palms up together: medium skin tone", "modifier", '🤲'},
	{"palms up together: medium", "modifier", '🤲'},
	{"palms up together: dark skin tone", "modifier", '🤲'},
	{"selfie: light skin tone", "modifier", '🤳'},
	{"selfie: medium", "modifier", '🤳'},
	{"selfie: medium skin tone", "modifier", '🤳'},
	{"selfie: medium", "modifier", '🤳'},
	{"selfie: dark skin tone", "modifier", '🤳'},
	{"prince: light skin tone", "modifier", '🤴'},
	{"prince: medium", "modifier", '🤴'},
	{"prince: medium skin tone", "modifier", '🤴'},
	{"prince: medium", "modifier", '🤴'},
	{"prince: dark skin tone", "modifier", '🤴'},
	{"person in tuxedo: light skin tone", "modifier", '🤵'},
	{"person in tuxedo: medium", "modifier", '🤵'},
	{"person in tuxedo: medium skin tone", "modifier", '🤵'},
	{"person in tuxedo: medium", "modifier", '🤵'},
	{"person in tuxedo: dark skin tone", "modifier", '🤵'},
	{"mrs", "modifier", '🤶'},
	{"mrs", "modifier", '🤶'},
	{"mrs", "modifier", '🤶'},
	{"mrs", "modifier", '🤶'},
	{"mrs", "modifier", '🤶'},
	{"person shrugging: light skin tone", "modifier", '🤷'},
	{"person shrugging: medium", "modifier", '🤷'},
	{"person shrugging: medium skin tone", "modifier", '🤷'},
	{"person shrugging: medium", "modifier", '🤷'},
	{"person shrugging: dark skin tone", "modifier", '🤷'},
	{"person cartwheeling: light skin tone", "modifier", '🤸'},
	{"person cartwheeling: medium", "modifier", '🤸'},
	{"person cartwheeling: medium skin tone", "modifier", '🤸'},
	{"person cartwheeling: medium", "modifier", '🤸'},
	{"person cartwheeling: dark skin tone", "modifier", '🤸'},
	{"person juggling: light skin tone", "modifier", '🤹'},
	{"person juggling: medium", "modifier", '🤹'},
	{"person juggling: medium skin tone", "modifier", '🤹'},
	{"person juggling: medium", "modifier", '🤹'},
	{"person juggling: dark skin tone", "modifier", '🤹'},
	{"person playing water polo: light skin tone", "modifier", '🤽'},
	{"person playing water polo: medium", "modifier", '🤽'},
	{"person playing water polo: medium skin tone", "modifier", '🤽'},
	{"person playing water polo: medium", "modifier", '🤽'},
	{"person playing water polo: dark skin tone", "modifier", '🤽'},
	{"person playing handball: light skin tone", "modifier", '🤾'},
	{"person playing handball: medium", "modifier", '🤾'},
	{"person playing handball: medium skin tone", "modifier", '🤾'},
	{"person playing handball: medium", "modifier", '🤾'},
	{"person playing handball: dark skin tone", "modifier", '🤾'},
	{"ninja: light skin tone", "modifier", '🥷'},
	{"ninja: medium", "modifier", '🥷'},
	{"ninja: medium skin tone", "modifier", '🥷'},
	{"ninja: medium", "modifier", '🥷'},
	{"ninja: dark skin tone", "modifier", '🥷'},
	{"leg: light skin tone", "modifier", '🦵'},
	{"leg: medium", "modifier", '🦵'},
	{"leg: medium skin tone", "modifier", '🦵'},
	{"leg: medium", "modifier", '🦵'},
	{"leg: dark skin tone", "modifier", '🦵'},
	{"foot: light skin tone", "modifier", '🦶'},
	{"foot: medium", "modifier", '🦶'},
	{"foot: medium skin tone", "modifier", '🦶'},
	{"foot: medium", "modifier", '🦶'},
	{"foot: dark skin tone", "modifier", '🦶'},
	{"superhero: light skin tone", "modifier", '🦸'},
	{"superhero: medium", "modifier", '🦸'},
	{"superhero: medium skin tone", "modifier", '🦸'},
	{"superhero: medium", "modifier", '🦸'},
	{"superhero: dark skin tone", "modifier", '🦸'},
	{"supervillain: light skin tone", "modifier", '🦹'},
	{"supervillain: medium", "modifier", '🦹'},
	{"supervillain: medium skin tone", "modifier", '🦹'},
	{"supervillain: medium", "modifier", '🦹'},
	{"supervillain: dark skin tone", "modifier", '🦹'},
	{"ear with hearing aid: light skin tone", "modifier", '🦻'},
	{"ear with hearing aid: medium", "modifier", '🦻'},
	{"ear with hearing aid: medium skin tone", "modifier", '🦻'},
	{"ear with hearing aid: medium", "modifier", '🦻'},
	{"ear with hearing aid: dark skin tone", "modifier", '🦻'},
	{"person standing: light skin tone", "modifier", '🧍'},
	{"person standing: medium", "modifier", '🧍'},
	{"person standing: medium skin tone", "modifier", '🧍'},
	{"person standing: medium", "modifier", '🧍'},
	{"person standing: dark skin tone", "modifier", '🧍'},
	{"person kneeling: light skin tone", "modifier", '🧎'},
	{"person kneeling: medium", "modifier", '🧎'},
	{"person kneeling: medium skin tone", "modifier", '🧎'},
	{"person kneeling: medium", "modifier", '🧎'},
	{"person kneeling: dark skin tone", "modifier", '🧎'},
	{"deaf person: light skin tone", "modifier", '🧏'},
	{"deaf person: medium", "modifier", '🧏'},
	{"deaf person: medium skin tone", "modifier", '🧏'},
	{"deaf person: medium", "modifier", '🧏'},
	{"deaf person: dark skin tone", "modifier", '🧏'},
	{"person: light skin tone", "modifier", '🧑'},
	{"person: medium", "modifier", '🧑'},
	{"person: medium skin tone", "modifier", '🧑'},
	{"person: medium", "modifier", '🧑'},
	{"person: dark skin tone", "modifier", '🧑'},
	{"child: light skin tone", "modifier", '🧒'},
	{"child: medium", "modifier", '🧒'},
	{"child: medium skin tone", "modifier", '🧒'},
	{"child: medium", "modifier", '🧒'},
	{"child: dark skin tone", "modifier", '🧒'},
	{"older person: light skin tone", "modifier", '🧓'},
	{"older person: medium", "modifier", '🧓'},
	{"older person: medium skin tone", "modifier", '🧓'},
	{"older person: medium", "modifier", '🧓'},
	{"older person: dark skin tone", "modifier", '🧓'},
	{"person: light skin tone", "modifier", '🧔'},
	{"person: medium", "modifier", '🧔'},
	{"person: medium skin tone", "modifier", '🧔'},
	{"person: medium", "modifier", '🧔'},
	{"person: dark skin tone", "modifier", '🧔'},
	{"woman with headscarf: light skin tone", "modifier", '🧕'},
	{"woman with headscarf: medium", "modifier", '🧕'},
	{"woman with headscarf: medium skin tone", "modifier", '🧕'},
	{"woman with headscarf: medium", "modifier", '🧕'},
	{"woman with headscarf: dark skin tone", "modifier", '🧕'},
	{"person in steamy room: light skin tone", "modifier", '🧖'},
	{"person in steamy room: medium", "modifier", '🧖'},
	{"person in steamy room: medium skin tone", "modifier", '🧖'},
	{"person in steamy room: medium", "modifier", '🧖'},
	{"person in steamy room: dark skin tone", "modifier", '🧖'},
	{"person climbing: light skin tone", "modifier", '🧗'},
	{"person climbing: medium", "modifier", '🧗'},
	{"person climbing: medium skin tone", "modifier", '🧗'},
	{"person climbing: medium", "modifier", '🧗'},
	{"person climbing: dark skin tone", "modifier", '🧗'},
	{"person in lotus position: light skin tone", "modifier", '🧘'},
	{"person in lotus position: medium", "modifier", '🧘'},
	{"person in lotus position: medium skin tone", "modifier", '🧘'},
	{"person in lotus position: medium", "modifier", '🧘'},
	{"person in lotus position: dark skin tone", "modifier", '🧘'},
	{"mage: light skin tone", "modifier", '🧙'},
	{"mage: medium", "modifier", '🧙'},
	{"mage: medium skin tone", "modifier", '🧙'},
	{"mage: medium", "modifier", '🧙'},
	{"mage: dark skin tone", "modifier", '🧙'},
	{"fairy: light skin tone", "modifier", '🧚'},
	{"fairy: medium", "modifier", '🧚'},
	{"fairy: medium skin tone", "modifier", '🧚'},
	{"fairy: medium", "modifier", '🧚'},
	{"fairy: dark skin tone", "modifier", '🧚'},
	{"vampire: light skin tone", "modifier", '🧛'},
	{"vampire: medium", "modifier", '🧛'},
	{"vampire: medium skin tone", "modifier", '🧛'},
	{"vampire: medium", "modifier", '🧛'},
	{"vampire: dark skin tone", "modifier", '🧛'},
	{"merperson: light skin tone", "modifier", '🧜'},
	{"merperson: medium", "modifier", '🧜'},
	{"merperson: medium skin tone", "modifier", '🧜'},
	{"merperson: medium", "modifier", '🧜'},
	{"merperson: dark skin tone", "modifier", '🧜'},
	{"elf: light skin tone", "modifier", '🧝'},
	{"elf: medium", "modifier", '🧝'},
	{"elf: medium skin tone", "modifier", '🧝'},
	{"elf: medium", "modifier", '🧝'},
	{"elf: dark skin tone", "modifier", '🧝'},
	{"pregnant man: light skin tone", "modifier", '🫃'},
	{"pregnant man: medium", "modifier", '🫃'},
	{"pregnant man: medium skin tone", "modifier", '🫃'},
	{"pregnant man: medium", "modifier", '🫃'},
	{"pregnant man: dark skin tone", "modifier", '🫃'},
	{"pregnant person: light skin tone", "modifier", '🫄'},
	{"pregnant person: medium", "modifier", '🫄'},
	{"pregnant person: medium skin tone", "modifier", '🫄'},
	{"pregnant person: medium", "modifier", '🫄'},
	{"pregnant person: dark skin tone", "modifier", '🫄'},
	{"person with crown: light skin tone", "modifier", '🫅'},
	{"person with crown: medium", "modifier", '🫅'},
	{"person with crown: medium skin tone", "modifier", '🫅'},
	{"person with crown: medium", "modifier", '🫅'},
	{"person with crown: dark skin tone", "modifier", '🫅'},
	{"hand with index finger and thumb crossed: light skin tone", "modifier", '🫰'},
	{"hand with index finger and thumb crossed: medium", "modifier", '🫰'},
	{"hand with index finger and thumb crossed: medium skin tone", "modifier", '🫰'},
	{"hand with index finger and thumb crossed: medium", "modifier", '🫰'},
	{"hand with index finger and thumb crossed: dark skin tone", "modifier", '🫰'},
	{"rightwards hand: light skin tone", "modifier", '🫱'},
	{"rightwards hand: medium", "modifier", '🫱'},
	{"rightwards hand: medium skin tone", "modifier", '🫱'},
	{"rightwards hand: medium", "modifier", '🫱'},
	{"rightwards hand: dark skin tone", "modifier", '🫱'},
	{"leftwards hand: light skin tone", "modifier", '🫲'},
	{"leftwards hand: medium", "modifier", '🫲'},
	{"leftwards hand: medium skin tone", "modifier", '🫲'},
	{"leftwards hand: medium", "modifier", '🫲'},
	{"leftwards hand: dark skin tone", "modifier", '🫲'},
	{"palm down hand: light skin tone", "modifier", '🫳'},
	{"palm down hand: medium", "modifier", '🫳'},
	{"palm down hand: medium skin tone", "modifier", '🫳'},
	{"palm down hand: medium", "modifier", '🫳'},
	{"palm down hand: dark skin tone", "modifier", '🫳'},
	{"palm up hand: light skin tone", "modifier", '🫴'},
	{"palm up hand: medium", "modifier", '🫴'},
	{"palm up hand: medium skin tone", "modifier", '🫴'},
	{"palm up hand: medium", "modifier", '🫴'},
	{"palm up hand: dark skin tone", "modifier", '🫴'},
	{"index pointing at the viewer: light skin tone", "modifier", '🫵'},
	{"index pointing at the viewer: medium", "modifier", '🫵'},
	{"index pointing at the viewer: medium skin tone", "modifier", '🫵'},
	{"index pointing at the viewer: medium", "modifier", '🫵'},
	{"index pointing at the viewer: dark skin tone", "modifier", '🫵'},
	{"heart hands: light skin tone", "modifier", '🫶'},
	{"heart hands: medium", "modifier", '🫶'},
	{"heart hands: medium skin tone", "modifier", '🫶'},
	{"heart hands: medium", "modifier", '🫶'},
	{"heart hands: dark skin tone", "modifier", '🫶'},
	{"leftwards pushing hand: light skin tone", "modifier", '🫷'},
	{"leftwards pushing hand: medium", "modifier", '🫷'},
	{"leftwards pushing hand: medium skin tone", "modifier", '🫷'},
	{"leftwards pushing hand: medium", "modifier", '🫷'},
	{"leftwards pushing hand: dark skin tone", "modifier", '🫷'},
	{"rightwards pushing hand: light skin tone", "modifier", '🫸'},
	{"rightwards pushing hand: medium", "modifier", '🫸'},
	{"rightwards pushing hand: medium skin tone", "modifier", '🫸'},
	{"rightwards pushing hand: medium", "modifier", '🫸'},
	{"rightwards pushing hand: dark skin tone", "modifier", '🫸'},
}
