// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trade.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Trade struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Symbol               string               `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Volume               int64                `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Price                float64              `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Buy                  bool                 `protobuf:"varint,5,opt,name=buy,proto3" json:"buy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_trade_a5b1dabc42416345, []int{0}
}
func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (dst *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(dst, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Trade) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Trade) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Trade) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetBuy() bool {
	if m != nil {
		return m.Buy
	}
	return false
}

func init() {
	proto.RegisterType((*Trade)(nil), "pb.Trade")
}

func init() { proto.RegisterFile("trade.proto", fileDescriptor_trade_a5b1dabc42416345) }

var fileDescriptor_trade_a5b1dabc42416345 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8d, 0xcb, 0xca, 0x83, 0x30,
	0x10, 0x85, 0x19, 0x6f, 0xfc, 0xff, 0xb8, 0x29, 0xa1, 0x94, 0xe0, 0xa6, 0xa1, 0xab, 0xac, 0x22,
	0xb4, 0x6f, 0x12, 0x7c, 0x01, 0xd3, 0xa6, 0x22, 0x18, 0x26, 0x68, 0x2c, 0xf8, 0x14, 0x7d, 0xe5,
	0x12, 0x2f, 0xbb, 0xf9, 0xce, 0x9c, 0x8f, 0x83, 0x65, 0x18, 0xdb, 0x97, 0x55, 0x7e, 0xa4, 0x40,
	0x2c, 0xf1, 0xa6, 0xba, 0x76, 0x44, 0xdd, 0x60, 0xeb, 0x35, 0x31, 0xf3, 0xbb, 0x0e, 0xbd, 0xb3,
	0x53, 0x68, 0x9d, 0xdf, 0x4a, 0xb7, 0x2f, 0x60, 0xde, 0x44, 0x89, 0x29, 0xcc, 0xe2, 0x93, 0x83,
	0x00, 0x59, 0xde, 0x2b, 0xb5, 0x99, 0xea, 0x30, 0x55, 0x73, 0x98, 0x7a, 0xed, 0xb1, 0x0b, 0x16,
	0xd3, 0xe2, 0x0c, 0x0d, 0x3c, 0x11, 0x20, 0xff, 0xf5, 0x4e, 0x31, 0xff, 0xd0, 0x30, 0x3b, 0xcb,
	0x53, 0x01, 0x32, 0xd5, 0x3b, 0xb1, 0x33, 0xe6, 0x7e, 0xec, 0x9f, 0x96, 0x67, 0x02, 0x24, 0xe8,
	0x0d, 0xd8, 0x09, 0x53, 0x33, 0x2f, 0x3c, 0x17, 0x20, 0xff, 0x74, 0x3c, 0x4d, 0xb1, 0x2e, 0x3e,
	0x7e, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xae, 0x9f, 0x1d, 0xcc, 0x00, 0x00, 0x00,
}
