[project]
name = "faster-pandas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.8"
dependencies = [
	'ipython',
	'numba',
	'pandas',
	'pyarrow',
	'pytest-benchmark',
]

[tool.ruff.format]
quote-style = "single"
