// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: unter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UnterClient is the client API for Unter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnterClient interface {
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type unterClient struct {
	cc grpc.ClientConnInterface
}

func NewUnterClient(cc grpc.ClientConnInterface) UnterClient {
	return &unterClient{cc}
}

func (c *unterClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/Unter/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnterServer is the server API for Unter service.
// All implementations must embed UnimplementedUnterServer
// for forward compatibility
type UnterServer interface {
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	mustEmbedUnimplementedUnterServer()
}

// UnimplementedUnterServer must be embedded to have forward compatible implementations.
type UnimplementedUnterServer struct {
}

func (UnimplementedUnterServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUnterServer) mustEmbedUnimplementedUnterServer() {}

// UnsafeUnterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnterServer will
// result in compilation errors.
type UnsafeUnterServer interface {
	mustEmbedUnimplementedUnterServer()
}

func RegisterUnterServer(s grpc.ServiceRegistrar, srv UnterServer) {
	s.RegisterService(&Unter_ServiceDesc, srv)
}

func _Unter_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnterServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Unter/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnterServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Unter_ServiceDesc is the grpc.ServiceDesc for Unter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Unter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Unter",
	HandlerType: (*UnterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _Unter_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unter.proto",
}
